version: "3"


services:
  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    hostname: localhost
    networks:
      - giftnetwork

    ports:
      - 8076:8076



  mysqlservice:
    image: mysql:latest
    container_name: mysql
    restart: always
    hostname: localhost
    networks:
      - giftnetwork
    ports:
      - 3307:3306

    environment:
      MYSQL_ROOT_PASSWORD: 'Aniket@1234'
      MYSQL_PASSWORD: Aniket@1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  gateway:
    build: api-gateway/
    container_name: api-gateway

    depends_on:
      - eureka-server
      - mysqlservice
    networks:
      - giftnetwork

    restart: always
    hostname: localhost
    ports:
      - 8080:8080



  product-webapp:
    build: product-webapp/
    image: product-webapp
    depends_on:
      - eureka-server
    networks:
      - giftnetwork
    restart: always
    container_name: product-webapp
    hostname: localhost
    ports:
      - 3001:3001



  job:
    build: job-service/
    container_name: job
    depends_on:
      - eureka-server
      - gateway
      - mysqlservice
    restart: always
    networks:
      - giftnetwork
    hostname: localhost
    ports:
      - 8081:8081



  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - giftnetwork
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - eureka-server
      - gateway
      - job


  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      restart: unless-stopped
      networks:
        - giftnetwork
      ports:
        - "3000:3000"
      links:
        - prometheus:prometheus

networks:
  giftnetwork:
    driver: bridge

